### ISSUE TITLE
Can buy land owned by other people

### ISSUE THREAD

**Issue by predawnia** [onebone/EconomyS#43] opened 2015-02-24 09:47 UTC
This is on the latest version on GitHub

- Can buy land owned by other people without any warning.
- Land will overlap in land.yml and the first land will have ownership of the overlapped land (example ID1: will own the land overlapped in ID2:)
- Owner of ID2 cannot edit land because of overlapped area belong to ID1

See: http://i.imgur.com/dVpnncp.png
Config: http://pastie.org/9977640

**Comment by onebone** [comment] 2015-02-26 05:09
What plugin was used to buy the land?

**Comment by predawnia** [comment] 2015-02-26 06:22
economy land from github

**Comment by onebone** [comment] 2015-02-26 07:51
Cannot reproduce the error. Did you registered the land in a proper way?

**Comment by predawnia** [comment] 2015-02-26 08:04
I used /startp, /endp and /land buy on the two IDs.
As you can see on the diagram I drew,  they are overlapping and the config
file shows the same too.

**Comment by onebone** [comment] 2015-03-05 12:53
Cannot reproduce the error. Could you send your EconomyLand plugin and data folder?

**Comment by cloud9350** [comment] 2015-03-12 11:30
아, 저거 저도 저러는데 다른사람과 구역이 겹치면 특정조건에 저런상황이 발생하더군요.
웬만한 평평한곳에는 잘 발생하지 않습니다.

**Comment by cloud9350** [comment] 2015-03-15 03:19
@onebone 위 댓글 확인부탁드려요

**Comment by dog194** [comment] 2016-01-25 17:16
maybe FIXED #219 @predawnia plz check and if so then close this issue

**Closed** 2016-08-08 08:22 UTC
Labels: bug
